### ISSUE TITLE
Not available via maven?

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#10]
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.google.cloud.tools%22

**Comment by patflynn** [comment]
FYI @loosebazooka 

@Burtan have you tried using the instructions for adding it to your build.gradle?  I think we've seen that the repo search can sometimes be out of date.

**Comment by loosebazooka** [comment]
This is only available in sonatype snapshots at the moment.

**Comment by patflynn** [comment]
@loosebazooka 
Does he need to add a special repository to make that work? It doesn't appear to be mentioned in the install instructions.

**Comment by Burtan** [comment]
I tried the instructions and got an error that the endpoints plugin was not available. I'm not familiar with sonatype so any further instructions are appreciated.

**Comment by loosebazooka** [comment]
I will update the instructions

**Comment by loosebazooka** [comment]
updated
