### ISSUE TITLE
Adding the client plugin to android application throws error

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#11]
Hi,

I've added the client plugin to my android application and running gradle now throws an error.

`apply plugin: 'com.google.cloud.tools.endpoints-framework-client'`
> Error:SourceSet with name 'main' not found.

Adding the client plugin to my java war application works fine.

**Comment by loosebazooka** [comment]
Yeah. There Android extensions are in progress. I'll have something
uploaded to snapshots later today with preliminary instructions

**Comment by loosebazooka** [comment]
Sorry this took longer than expected, had to figure out how to interact correctly with the android model. Instructions will go up tomorrow.

**Comment by Burtan** [comment]
`endpointsServer project(path: ":server", configuration: "endpoints")`
It's working fine now
