### ISSUE TITLE
Update to newest endpoints version beta-12

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#14]
Hi, 
please update the endpoints framework dependency to beta-12.
See:
https://github.com/cloudendpoints/endpoints-java/issues/29

**Comment by loosebazooka** [comment]
Hopefully I can get reviews on #15 during the weekend, but in the meantime you can just force that version in the buildscript classpath, so the plugin is also forced to use it.

```gradle
buildscript {
  ...
  dependencies {
    // force the pluging to use endpoints tools 2.0.0-beta.12
    classpath "com.google.endpoints:endpoints-framework-tools:2.0.0-beta.12"
    classpath "com.google.cloud.tools:endpoints-framework-gradle-plugin:1.0.0-beta"
  }
}

**Comment by Burtan** [comment]
Thanks, I'll try that. I think that is the last issue for me now :-)

**Comment by loosebazooka** [comment]
I think there's actually an issue there. Locating the webapp (or war)
directory seems to be malfunctioning

**Comment by Burtan** [comment]
Gradle sync now completes for me but building the android app results in an error:

> Error:Execution failed for task ':app-backend:endpointsDiscoveryDocs'.
> Could not initialize class com.google.api.server.spi.tools.GenClientLibAction

**Comment by loosebazooka** [comment]
If you do an "assemble" I think you'll get a better error message, I don't think the plugin is fully compatible yet with beta11/12. Hopefully the endpoints-tools issue mentioned in #15 is fixable.

**Comment by Burtan** [comment]
Here is the error message I get with assemble:

> Error:Execution failed for task ':app-backend:endpointsDiscoveryDocs'.
> com.google.api.server.spi.ObjectMapperUtil.createStandardObjectMapper()Lcom/fasterxml/jackson/databind/ObjectMapper;

**Comment by Burtan** [comment]
The error message is gone with beta2 thanks
