### ISSUE TITLE
JavaClient changes

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#17]
Hi,
my android app with dependency on endpoints v2 now compiles but there seem to be some changes to the v1 client.

Objects don't use type Long but String (extraction from the discovery doc):

``` 
"MyObject": {
   "id": "MyObject",
   "type": "object",
   "properties": {
    "id": {
     "type": "string",
     "format": "int64"
    }
   }
  },
```

```
public static class MyObject {
        public Long id;
}
```

**Comment by loosebazooka** [comment]
You should probably file this here : https://github.com/cloudendpoints/endpoints-java @tangiel might have a better idea of what's going on.
