### ISSUE TITLE
Using the server plugin with flexible environment

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#20]
Hi,
I've just tried to use the server plugin with an GAE java flexible environment. I'm getting the following error:

Error:Execution failed for task ':flexbackend:endpointsDiscoveryDocs'.
> Line 1, column 4: Unable to find property 'env' on class: com.google.apphosting.utils.config.AppYaml

app.yaml
```
runtime: java
env: flex
service: dbanalyzer
manual_scaling:
  instances: 1
```

**Comment by loosebazooka** [comment]
@tangiel any idea?

**Comment by Burtan** [comment]
I think I could figure out for me. I was always using appengine-web.xml instead of app.yaml, but in the flexible [environment doc](https://cloud.google.com/appengine/docs/flexible/java/configuring-your-app-with-app-yaml), only app.yaml is mentioned. Additionally this gradle plugin shows "app engine standard environment" instead of "app engine flexible environment" even though you configure flex in appengine-web.xml. I just realized that app.yaml does not belong into the WEB-INF folder but in a dedicated appengine-folder placed directly under main. So with app.yaml in the correct folder, the error mentioned above is gone, but instead the plugin is now asking for an appengine-web.xml file. 
So I removed all the app.yaml stuff and just reverted back fully to appengine-web.xml. When trying to deploy it now, it correctly uses the flex environment declared in appengine-web.xml despite the folder being named "app engine standard environment".

**Comment by loosebazooka** [comment]
Right, for actual flexible environment applications, you're not expected to use the dev-appserver, you use the app server defined in your runtime (like jetty or whatever). Additionally, for an application that is detected to be a flexible style app, no server goals will be provided by the appengine plugin.

When using flex in appengine-web.xml, it is still considered an appengine standard style application (that is being deployed on the flexible environment.. the naming is a little confusing here).
@patflynn  @ludo @arouzrokh what's the status of using env flex in appengine-web.xml?

What exactly were you trying to deploy here? A completely custom web-application on the flex environment? or an appengine (with all built-in appengine APIs) app on flex?

**Comment by Burtan** [comment]
It's an appengine app which I need to run on the flex environment because I need local filesystem access.

**Comment by Burtan** [comment]
Ah ok. When defining app.yaml it's still asking for appengine-web.xml because I use appengine APIs.

**Comment by Burtan** [comment]
Actually, the deployment is not working when just using the appengine-web.xml with flex being defined (it works with the old plugin, where I could create the staged app and then manually deploy with gcloud). I'm getting the following error: 

```
ERROR: (gcloud.app.deploy) Error Response: [9] 
Application startup error:
Info: Limiting Java heap size to: 400M
2017-01-17 18:30:01.661:INFO::main: Logging initialized @528ms
2017-01-17 18:30:03.088:INFO:oejs.Server:main: jetty-9.3.5.v20151012
2017-01-17 18:30:03.603:INFO:oejs.AbstractNCSARequestLog:main: Opened /var/log/app_engine/request.2017_01_17.log
Jan 17, 2017 6:30:04 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: http://metadata/computeMetadata/v1/instance/attributes/gae_affinity
Jan 17, 2017 6:30:04 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_appengine_hostname' path retrieval error: http://metadata/computeMetadata/v1/instance/attributes/gae_appengine_hostname
```

**Comment by loosebazooka** [comment]
@arouzrokh can confirm here, but I think that standard applications on flex environments was experimental and never went passed that. https://cloud.google.com/appengine/docs/flexible/java/migrating if you want to use flex, you're going to have to use the actual non-appengine specific api.

**Comment by Burtan** [comment]
Ok, thanks

**Comment by patflynn** [comment]
`<env>flex</env>  ` in your appengine-web.xml is indeed not the recommended way to use flex and will not have long term support.  But it should work currently.

you should be able to deploy using the new  [app-gradle-plugin](https://github.com/GoogleCloudPlatform/app-gradle-plugin)

**Comment by Burtan** [comment]
But endpoints is supposed to be supported on [flexible environments in the long run](https://cloud.google.com/endpoints/docs/quickstart-app-engine)? Because it currently seems to depend on appengine-web.xml

```
Error:Execution failed for task ':flexbackend:endpointsDiscoveryDocs'.
> Could not locate /home/frederik/AndroidStudio/flexbackend/src/main/webapp/WEB-INF/appengine-web.xml
```

**Comment by loosebazooka** [comment]
endpoints-framework is a transition plugin for existing users of legacy endpoints, it's only built for standard appengine applications.

It is not recommended for new development.

**Comment by Burtan** [comment]
Ok, now I'm a little bit confused. This new plugin is meant to be only for legacy endpoints (v1?).

**Comment by loosebazooka** [comment]
Right, the document you linked to is for endpoints v2, it doesn't require any special processing from the gradle tooling. 

endpoints-framework-gradle-plugin is only for v1 as a mechanism to support existing users of endpoints v1 with newer appengine tooling.

**Comment by Burtan** [comment]
So I guess this guide is still refering to v1? 
https://cloud.google.com/endpoints/docs/frameworks/java/calling-from-android
Because it is on the new documentation page.

**Comment by loosebazooka** [comment]
Yes, you are correct. @arouzrokh, @tangiel what do we want to do about this documentation?

**Comment by Burtan** [comment]
Actually the whole https://cloud.google.com/endpoints/docs/frameworks/java/* part looks to be v1? I think it is very confusing to mix documentation about v1 and v2 at one place.

**Comment by loosebazooka** [comment]
@lesv for documentation?

**Comment by lesv** [comment]
Actually - sending doc requests to me won't help you.  Can you engage Jimmy on all this stuff?

**Comment by frankyn** [comment]
~~@loosebazooka  I'm confused, this plugin supports OpenAPI spec generation which is part of EP frameworks v2. I received confirmation for using this plugin with V2 samples. Is this incorrect?~~

This was posted back on January 18, I missed that. Please ignore my comment.

**Comment by Burtan** [comment]
> endpoints-framework-gradle-plugin is only for v1 as a mechanism to support existing users of endpoints v1 with newer appengine tooling.

I still don't get this. Cloud Endpoints Framework 2.0 for AppEngine Standard stills seems to depend on this plugin and therefore it is not only for legacy users?

**Comment by patflynn** [comment]
@Burtan.  The quote is a little misleadiing/inaccurate because it conflates the framework with v1.  

This plugin supports the Java endpoints framework users that migrate to V2.  So the plugin does support Endpoints V2 users that are using the Java endpoints framework.

**Comment by Burtan** [comment]
> endpoints-framework is a transition plugin for existing users of legacy endpoints, it's only built for standard appengine applications.
> It is not recommended for new development.

As far as I understand the docs, the only way to use endpoints v2 on standard app engine is this plugin. Thus for new development, standard app engine is not recomended anymore? Is compute engine the only way to go?

**Comment by patflynn** [comment]
@Burtan standard app engine is definitely recommended for new development!  I believe @loosebazooka was referring to the endpoints-framework when he suggested not using it for new development.  I believe the endpoints-framework is still supported but I am not certain to what extent it will be in the future.

**Comment by loosebazooka** [comment]
perhaps @tangiel might have some more info?

**Comment by tangiel** [comment]
@Burtan strictly speaking, this plugin is not necessary for anything. It is mostly a build-system-friendly plugin that provides tasks that the Endpoints framework tool exposes. You can use the framework without the plugin, it's just not recommended. If your goal is to take advantage of the Endpoints console in Cloud Console, then the framework (and this plugin, if you desire) are currently your only option. If your goal is just to write an API, there are other options that you may want to evaluate. The Endpoints framework is pretty opinionated, so it lacks the flexibility of some of the other frameworks.
