### ISSUE TITLE
Generate the discovery docs in rpc format

### ISSUE THREAD

**Issue by daswass** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#21]
I just converted from the gradle-appengine-plugin to use a combination of the new app-gradle-plugin and endpoints-framework-gradle-plugin. I am using appengine with endpoints as a backend for my ios app. 

In the past, I would generate the rpc discovery docs and then use the Google ServiceGenerator. Will this plugin provide the rpc discovery doc or do I need to update now to use https://github.com/google/google-api-objectivec-client-for-rest?

**Comment by loosebazooka** [comment]
@tangiel

From what I know, there is no more rpc discovery doc generation. I believe you will now need to use the rest doc for client generation. @tangiel should have a better idea though.

**Comment by tangiel** [comment]
Yes that's correct, RPC generation has been removed in the new framework. You should update to use the new Objective C REST client, as you suggested.

**Comment by daswass** [comment]
@tangiel, using the rest discovery doc, Im having an issue with the new ServiceGenerator. It looks like the discovery doc generated is missing a format tag where it is expected. Please see the linked issue here: https://github.com/google/google-api-objectivec-client-for-rest/issues/85

After manually updating the discovery doc for all double values (type is number - add missing format key and double value), the generator completes successfully. This could be a bug in the discovery doc generator.

**Comment by daswass** [comment]
Has anybody gotten a chance to take a look at the generator? Is there another group that works on the actual generator code? Thanks in advance.

**Comment by patflynn** [comment]
@redi-wassere @tangiel Endpoints team should know where the generator code lives.

**Comment by daswass** [comment]
My mistake, its the generated discovery doc that is the issue. Unless I am missing a flag or something, I believe there is an issue with discovery docuement generation, where it doesn't create the '"format": "double' for double fields. creditAmount below should have the format tag. See:

```
"creditKickbackKash": {
     "httpMethod": "PUT",
     "id": "servUsApi.admin.creditKickbackKash",
     "parameterOrder": [
      "userId",
      "creditAmount"
     ],
     "parameters": {
      "userId": {
       "format": "int64",
       "location": "path",
       "required": true,
       "type": "string"
      },
      "creditAmount": {
       "location": "path",
       "required": true,
       "type": "number"
      }
     },
     "path": "creditKickbackKash/{userId}/{creditAmount}",
     "response": {
      "$ref": "ResultDTO"
     },
     "scopes": [
      "https://www.googleapis.com/auth/userinfo.email"
     ]
    }
```

**Comment by loosebazooka** [comment]
@tangiel can you take a look at this?

**Comment by tangiel** [comment]
@loosebazooka the format issue should be fixed already in the last few versions of the framework.

**Comment by loosebazooka** [comment]
Okay thanks! Closing this for now.

**Comment by daswass** [comment]
Yes, looks good to me! Thanks all
