### ISSUE TITLE
Set the directory where Generated Client is located 

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#22]
Hi,

Is there a way to set the path of the generated client is located?

There's a parameter for this in the [maven version of this plugin](https://github.com/GoogleCloudPlatform/endpoints-framework-maven-plugin). 

Maven-example:
```
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>endpoints-framework-maven-plugin</artifactId>
  <configuration>
    <clientLibDir>.</clientLibDir>
  </configuration>
</plugin>
```

Thank you!

**Comment by loosebazooka** [comment]
Looks like that configuration parameter is final in gradle and cannot be modified at the moment. Is this for the docs?
