### ISSUE TITLE
App Engine Gradle plugin warns about application tag usage

### ISSUE THREAD

**Issue by UweTrottmann** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#30]
Endpoints discovery docs generation (server side) requires the `<application>` tag to be used in the `appengine-web.xml` file. However, the new [App Engine Gradle plugin](https://github.com/GoogleCloudPlatform/app-gradle-plugin) warns that in a future version deploying with `<application>` or `<version>` present will fail.

```
Reading application configuration data...
*********************************
Configuration Warning : <application> XML element and --application should not be specified when staging

The following parameters will be scrubbed from app.yaml
application : <redacted>

Future versions of staging will fail if application or version is specified.
*********************************
```

Searching for this log output did not turn up anything in the Gradle plugin source code, so this warning is probably coming from a Cloud SDK component.

Or am I missing a configuration option to set the project ID differently?

**Comment by patflynn** [comment]
@loosebazooka 

Hi @UweTrottmann! Thanks for the report.  Are you sure that doc generation doesn't work without the `application` element? I thought I'd tried this a while back and the only thing broken was the devappserver needed <version> or it would fail. Deployments worked fine though.

**Comment by UweTrottmann** [comment]
Yes. If the application tag is missing, when running the `endpointsDiscoveryDocs` task the generated `<endpoint>-rest.discovery` file will use a **default value of `myapp`** used for `baseUrl` and `rootUrl`:
```
[...]
"baseUrl": "https://myapp.appspot.com/_ah/api/<endpoint>/<version>/",
[...]
"rootUrl": "https://myapp.appspot.com/_ah/api/",
[...]
```

Client side, endpoints library generation will then use that wrong root URL:
`public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";`

**Comment by patflynn** [comment]
@loosebazooka how do our new endpoints plugins handle this?

**Comment by loosebazooka** [comment]
Yeah this is a bug. I'll see if we can pass the project into the endpoints generation tool. If not, we'll push a change to endpoints-framework-tools to do it.

**Comment by loosebazooka** [comment]
The workaround is to specify the root-url explicitly when using the client library
```
MyApi.Builder builder = new MyApi.Builder(...).setRootUrl("url here")
```

**Comment by loosebazooka** [comment]
@tangiel can we add this as a configurable parameter in the tooling?

**Comment by loosebazooka** [comment]
@UweTrottmann I think you're going to have to leave the applicationid in for now (even though it is ignored for deployment) to create the client library the way you want. We'll mark this as a bug, and try to fix as soon as the endpoints team gets back to us.

**Comment by UweTrottmann** [comment]
@loosebazooka Not a problem. Just wanted to give you a heads up about the warning.

**Comment by loosebazooka** [comment]
@UweTrottmann This should be fixed by #37 and in the beta8 release. So now you can explictly define the hostname "myapp.appspot.com" in the gradle config to override the default.

**Comment by UweTrottmann** [comment]
@loosebazooka Yeap, works as documented. 👍

**Comment by loosebazooka** [comment]
I'll go ahead and close this issue now then.
