### ISSUE TITLE
Client generation from discovery doc is not added to sources on Android Studio 2.3

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#31]
Hi, 
I have a module that creates an endpoints java client api from a discovery doc which I'm using in an IntelliJ IDEA 2016.3.5 project and an Android Studio 2.3 project. In both projects, the client java files are correctly generated but only for the IntelliJ project, the generated java files in the build folder are added to the sources of the module so that they can be imported and used.
Any ideas?

**Comment by loosebazooka** [comment]
Right, it has something to do with how android allows generated source directories. It looks like I forgot to document this. (this is not true)

~~but after you apply the endpoints-framework-client, you need to apply endpoints-framework-android-client to add in the android extensions that deal with android related shenanigans.~~

```
apply plugin: 'endpoints-framework-client'
apply plugin: 'endpoints-framework-android-client'
```

~~I should probably just auto apply the endpoints-framework-client in the endpoints-framework-android-client by default. But I think this is what you need for now.~~

**Comment by Burtan** [comment]
When trying to add:
```apply plugin: 'com.google.cloud.tools.endpoints-framework-android-client'```
I get:
```Error:(3, 0) Extension with name 'android' does not exist. Currently registered extension names: [ext, defaultArtifacts, reporting, endpointsClient]```
And my module is plain java and not the app module but just a library, if that is important.

**Comment by loosebazooka** [comment]
yeah I think I gave you bad information. We already auto apply the android extensions for android projects when needed. :\

I wonder if android studio just doesn't allow this stuff in general unless it's in their arbitrarily defined generated sources directory.

**Comment by loosebazooka** [comment]
Does the command line build fail?

**Comment by Burtan** [comment]
The command line build succeeds and I can even run the app but the editor still complains about non-resolved imports. So I guess it's a synchronization issue between the IDE and gradle.

**Comment by loosebazooka** [comment]
Ugh, that's unfortunate. Can you try switch the generatedSrcDir to something that android studio likes?

```Groovy
endpointsClient {
  genSrcDir = new File("${buildDir}/generated/source/endpoints")
}
```

**Comment by Burtan** [comment]
The problem remains with the custom source dir

**Comment by loosebazooka** [comment]
I'm not sure, can you make it an "android-library" instead of a java library? Presumably then we'll register the correct generated source configuration.

Otherwise I would ask the android team how to correctly register generated source with the IDE from a java library?

**Comment by Burtan** [comment]
```
apply plugin: 'com.android.library'
apply plugin: 'com.google.cloud.tools.endpoints-framework-client'
```
throws 
```
Error:(3, 0) Could not get unknown property 'applicationVariants' for object of type com.android.build.gradle.LibraryExtension.
```

```
apply plugin: 'com.android.library'
apply plugin: 'com.google.cloud.tools.endpoints-framework-android-client'
```
throws
`Error:(4, 0) Cannot set property 'genSrcDir' on null object`

**Comment by loosebazooka** [comment]
Alright, looks like we didn't handle com.android.library correctly, but when fixing that, I found another bug where the server side wasn't generating artifacts required for android clients because of some madness in the android plugin. This should all be fixed now. I'll push an update soon.

**Comment by loosebazooka** [comment]
@Burtan This should be fixed in the 1.0.0-beta7 release that just went out.

**Comment by Burtan** [comment]
Actually the plugin still throws the same errors.

**Comment by Burtan** [comment]
Any progress?

**Comment by loosebazooka** [comment]
Which error are you continuing to see?

**Comment by loosebazooka** [comment]
@Burtan I checked again with `1.0.0-beta7` and this works with modules that are explicitly 'com.android.library' not regular java plugins.

I don't know if there's even a way to register code generation tasks with android for non-android libraries modules.

**Comment by Burtan** [comment]
I've tried again with 1.0.0-beta8:

```
apply plugin: 'com.android.library'
apply plugin: 'com.google.cloud.tools.endpoints-framework-android-client'
```
throws: 
```
java.lang.IllegalStateException: buildToolsVersion is not specified.
...
> Failed to apply plugin [id 'com.google.cloud.tools.endpoints-framework-android-client']
   > Cannot set property 'genSrcDir' on null object
```

So I've added 

```
android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'
}
```
but the error remains

**Comment by loosebazooka** [comment]
Oh I see, it looks like it's this line? https://github.com/GoogleCloudPlatform/endpoints-framework-gradle-plugin/blob/master/src/main/groovy/com/google/cloud/tools/gradle/endpoints/framework/client/AndroidEndpointsClientPlugin.groovy#L35 It's weird that it wouldn't work for you, but it works for me. Any chance you could send over a mimized version of the project. There's no reason that `endpointsClient` should be null there.

**Comment by loosebazooka** [comment]
ooh oh, I see. Yeah don't apply `endpoints-framework-android-client` directly. That's automatically applied by the `endpoints-framework-client` if android is detected.

So you should be doing
```
apply plugin: 'com.android.library'
apply plugin: 'com.google.cloud.tools:endpoints-framework-client'
```

**Comment by Burtan** [comment]
```
apply plugin: 'com.android.library'
apply plugin: 'com.google.cloud.tools.endpoints-framework-client'

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 25
    }
}
```

This configuration now works on Android Studio with an empty AndroidManifest.xml for the library. But it doesn't work for IntelliJIDEA anymore, because my project there relies on the jar task from the java plugin. Therefore it would be a much cleaner solution if Android Studio could deal with a java endpoints library.

**Comment by loosebazooka** [comment]
I've started a bug there regarding generated source from a plain java module, please follow up on the android studio issue tracker : https://issuetracker.google.com/issues/37778124

**Comment by Burtan** [comment]
Thanks, I'll observe it.
