### ISSUE TITLE
[Feature Request] Use gcloud tool project id default for hostname

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#46]
Hi,

It would be helpful for the default Project ID for hostname `project-id.appspot.com` to come from the gcloud tool instead of the plugin configuration.

**Comment by patflynn** [comment]
I think that would work pretty well in lots of cases, but I'm concerned that users who have lots of projects and frequently switch default gcloud projects will be bitten by this.  It seems generally poor form to have a hidden and obscure source of input into the build.

**Comment by frankyn** [comment]
@patflynn, I don't mean for this request to be the only way for input of a hostname. I'm pushing to have it automatically filled in using the gcloud settings or configured/set inside in the build.gradle. I can update the sample and plugin documentation to call this functionality explicitly. 

Does this sound reasonable?

**Comment by patflynn** [comment]
I'm not sure at this point. Curious to hear what @loosebazooka thinks. (although he's out of the office for a few weeks).

Not sure I understand what you mean by 'I can update the sample and plugin documentation to call this functionality explicitly.'

**Comment by loosebazooka** [comment]
The endpoints plugin has no knowledge of gcloud. I would just use the
"hostname" parameter for now in the build.gradle. perhaps this is a problem
we should look at some more though.

**Comment by frankyn** [comment]
@patflynn Oh okay, it's not urgent and we can talk more about it when @loosebazooka gets back. Follow-up to your last statement. I currently use "hostname" in the [migration sample](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine/endpoints-frameworks-v2/migration-example/build.gradle#L77). The main difference with this FR is the `hostname` line would look similar to:

```
endpointsServer {
  // Endpoints Framework Plugin server-side configuration
  // Hostname is automatically defined by Cloud SDK as YOUR-PROJECT-ID.appspot.com
  //     and can also be defined by uncommenting the next line.
  // hostname = "YOUR-PROJECT-ID.appspot.com"
}
```
