### ISSUE TITLE
Unexpected method parameter order for generated client library

### ISSUE THREAD

**Issue by gbhall** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#48]
I've migrated to this plugin from the legacy plugin, however some calls to my API are now broken in my Android project due to some method parameters being reordered. 

Take this endpoint example:
```java
    @ApiMethod(name = "x.location.nearby.list", httpMethod = "GET", path = "entityx/nearby")
    public Collection<EntityX> listNearbyX(@Named("latitude") final double latitude, @Named("longitude") final double longitude, @Named("radius") int radius, @Named("dev") @DefaultValue("") String dev, User user)
```

Calling the endpoint before had the order: 
`Double latitude, Double longitude, Integer radius`.
Now the order is:  
`Double latitude, Integer radius, Double longitude`.

Is there an ordering logic behind this? It's not the written order, or alphabetical. 

In my `@ApiMethod` removing `path = "entityx/nearby"` restores the expected parameter ordering in my Android project. However I want to continue to utilise `path`.

**Comment by loosebazooka** [comment]
@tangiel any idea here?

**Comment by tangiel** [comment]
@gbhall What version of the frameworks are you using?

**Comment by gbhall** [comment]
@tangiel For my `app/build.gradle`:
```
com.google.cloud.tools:endpoints-framework-gradle-plugin:+

com.google.api-client:google-api-client:1.22.0
com.google.http-client:google-http-client-android:1.22.0
[group: 'com.google.api-client', name: 'google-api-client-android', version: '1.22.0']
```

**Comment by tangiel** [comment]
I don't see an explicit dependency on `endpoints-framework` in there. Can you post that?

**Comment by gbhall** [comment]
@tangiel for my backend module dependencies?

For `backend/build.gradle` each dependency version I am using is `+`:
```
    // App Engine Gradle plugin
    classpath 'com.google.cloud.tools:appengine-gradle-plugin:+'

    // Endpoints Frameworks Gradle plugin
    classpath 'com.google.cloud.tools:endpoints-framework-gradle-plugin:+'

    // AppEngine
    compile group: 'com.google.appengine', name: 'appengine-api-1.0-sdk', version: '+'
    compile 'javax.servlet:servlet-api:2.5'

    //  Cloud Endpoints Framework
    providedCompile group: 'javax.servlet', name: 'servlet-api', version:'2.5'
    compile 'jstl:jstl:1.2'
    compile group: 'javax.inject', name: 'javax.inject', version: '1'
    compile group: 'com.google.endpoints', name: 'endpoints-framework', version: '+'
    compile group: 'com.google.endpoints', name: 'endpoints-management-control-appengine', version: '+'
    compile group: 'com.google.endpoints', name: 'endpoints-framework-auth', version: '+'
```

**Comment by loosebazooka** [comment]
Oh also the tooling (endpoints-framework-gradle-plugin) comes from the plugin, we use 2.0.7

**Comment by gbhall** [comment]
@loosebazooka Are you asking me to explicitly specify version `2.0.7` in my `build.gradle` files, or was that information for @tangiel?

**Comment by loosebazooka** [comment]
Information for @tangiel

**Comment by gbhall** [comment]
@loosebazooka Thanks for the clarification

**Comment by tangiel** [comment]
@gbhall sorry for the slow reply. Can you run on devserver and go to `http://localhost:8080/_ah/discovery/v1/apis/API-NAME-HERE/API-VERSION-HERE/rest`, search for `listNearbyX`, and paste the JSON object value here? It should include things like path, parameters, etc.

**Comment by gbhall** [comment]
No problem. Just a FYI the URL provided didn't work, what did work was:
localhost:8080/_ah/`api/`discovery/v1/apis/API-NAME-HERE/API-VERSION-HERE/rest

@tangiel:
```
     "resources": {
      "nearby": {
       "methods": {
        "list": {
         "httpMethod": "GET",
         "id": "Zzz.xxx.location.nearby.list",
         "parameters": {
          "latitude": {
           "format": "double",
           "location": "query",
           "required": true,
           "type": "number"
          },
          "longitude": {
           "format": "double",
           "location": "query",
           "required": true,
           "type": "number"
          },
          "radius": {
           "format": "int32",
           "location": "query",
           "required": true,
           "type": "integer"
          },
          "dev": {
           "default": "",
           "location": "query",
           "type": "string"
          }
         },
         "path": "entityxxx/nearby",
         "response": {
          "$ref": "EntityXxxCollection"
         },
         "scopes": [
          "https://www.googleapis.com/auth/userinfo.email"
         ]
        }
       }
      }
     }
```

**Comment by loosebazooka** [comment]
@tangiel any ideas? @gbhall is this still an issue?

**Comment by gbhall** [comment]
@loosebazooka Still unresolved as far as I know.

**Comment by tangiel** [comment]
It's a frameworks issue, I will work on a fix.

**Comment by gbhall** [comment]
Cheers Daniel.

**Comment by tangiel** [comment]
Fix is in PR: https://github.com/cloudendpoints/endpoints-java/pull/113

**Comment by tangiel** [comment]
Frameworks 2.0.9 is being released to Maven now. This should fix your issue, but let me know if it doesn't. Also, please file against https://github.com/cloudendpoints/endpoints-java if it doesn't.

**Comment by loosebazooka** [comment]
@gbhall you can test this by explicitly applying the dependency in the buildscript classpath

```
buildscript {
  repositories {
    ...
  }
  dependecies {
     ...
     classpath 'com.google.endpoints:endpoints-framework-tools:2.0.9'
     // pulled in automatically 'com.google.endpoints:endpoints-framework:2.0.9'
  }
}
