### ISSUE TITLE
Feature request:  Deploy openApi json to appengine with gradle

### ISSUE THREAD

**Issue by medvedev** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#64]
Hi,
I guess it's a good feature to deploy OpenApi spec to GAE with Gradle, in the way similar to "appengineDeploy*" tasks work for "general" gradle appengine plugin.
I.e. I'd like to have a gradle replacement to "gcloud service-management deploy {path to openApi.json}"

**Comment by patflynn** [comment]
is this necessary for app engine standard?

**Comment by medvedev** [comment]
@patflynn I don't have enough information to answer your question.
At the moment I can't say if there's any difference between following cases:  
1) App is deployed with `appengineDeploy` gradle task
2) App is deployed by `appengineDeploy` followed API deploy
3) API is deployed first, then App is deployed with `appengineDeploy`

Assuming that:
- "App" is GAE SE app with Endpoints features  (Endpoints servlet and filters, @Api-annotated classes)
- "API deploy" is CLI command: `gcloud service-management deploy ./build/endpointsOpenApiDocs/openapi.json`

So, IMO, it's up to you to decide if this feature is something that might be useful for Endpoints users.

**Comment by medvedev** [comment]
What I've observed so far: API deployment (Deployment history section), endpoints (in the bottom of overview) and stats are not visible in Endpoints WEB UI (https://console.cloud.google.com/endpoints) until `gcloud service-management deploy ....` is executed.
So, "appengineDeploy" alone does not have full endpoints support for appengine SE.

**Comment by patflynn** [comment]
@tangiel

**Comment by tangiel** [comment]
It's up to you guys if you want to support this command, but it is not strictly necessary. This refers to the management library, which are separate from the core framework library, which is what this plugin is intended to support.

**Comment by patflynn** [comment]
@loosebazooka 

It doesn't sound totally unreasonable. However it does sound that we may want similar functionality for Endpoints v2 users who aren't using the framework.
