### ISSUE TITLE
Feature: add API validation for tasks

### ISSUE THREAD

**Issue by medvedev** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#65]
Please feel free to forward this issue to an appropriate repository\project\team.
Here's one more confusing scenario.
I've renamed one named parameter in java API class and added hyphen "-" in the middle of the name. So it looked like:
`public void apiMethod(@Named("foo-bar") String fooBar)`

I got no issues when openApi.json was generated or when app was deployed to appengine, but was not able to see my API in API explorer web UI.
To find out what's wrong I had to dig into logs, and there I've found this:
`...
java.lang.IllegalArgumentException: 'foo-bar' not a valid path parameter name at at com.google.api.server.spi.dispatcher.PathTrie$Builder.getAndCheckParameterName(PathTrie.java:221) at com.google.api.server.spi.dispatcher.PathTrie$Builder.add(PathTrie.java:190) at com.google.api.server.spi.dispatcher.PathTrie$Builder.add(PathTrie.java:202) at com.google.api.server.spi.dispatcher.PathTrie$Builder.add(PathTrie.java:202) at com.google.api.server.spi.dispatcher.PathTrie$Builder.add(PathTrie.java:202) at com.google.api.server.spi.dispatcher.PathTrie$Builder.add(PathTrie.java:176) at com.google.api.server.spi.dispatcher.PathDispatcher$Builder.add(PathDispatcher.java:69) at com.google.api.server.spi.EndpointsServlet.createDispatcher(EndpointsServlet.java:109) at com.google.api.server.spi.EndpointsServlet.init(EndpointsServlet.java:58)...`
I guess, the problem is clear.
IMO, validation should be performed when openApi.json is generated. Or, alternatively, some validation fixed in the deep of Endpoints platform.

**Comment by patflynn** [comment]
@tangiel thoughts on this?  do you know where the FR should live?

**Comment by tangiel** [comment]
I believe validation is done, it just doesn't check this case for some reason. This would be a bug to file under https://github.com/cloudendpoints/endpoints-java.

**Comment by medvedev** [comment]
Thank you @tangiel 
I've created a new issue [(#107)](https://github.com/cloudendpoints/endpoints-java/issues/107) for Endpoints framework.
This one can be closed now.
