### ISSUE TITLE
Plugin not compatible with "gcloud service-management deploy..."

### ISSUE THREAD

**Issue by Aardvarklord** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#73]
Steps to reproduce:

1. Add `apiKeyRequired = AnnotationBoolean.TRUE` to the endpoints API
2. Use the plugin to generate the openapi.json file
3. Deploy the API by running `gcloud service-management deploy .\build\endpointsOpenApiDocs\openapi.json`

Warnings like this are shown:
_WARNING: openapi.json: Operation 'put' in path 'XXXXXXXXX': Operation does not require an API key; callers may invoke the method without specifying an associated API-consuming project. To enable API key all the SecurityRequirement Objects (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-requirement-object) inside security definition must reference at least one SecurityDefinition of type : 'apiKey'._

The openapi.json file generated by the plugin contains this:
```
"security": [
     {
      "firebase": [ ]
     },
     {
      "api_key": [ ]
     }
    ],
```
If I edit the openapi.json file to this the warnings disappear:
```
"security": [
     {
      "firebase": [ ],
      "api_key": [ ]
     }
    ],

```

**Comment by loosebazooka** [comment]
@tangiel

**Comment by tangiel** [comment]
@Aardvarklord please file a bug at https://github.com/cloudendpoints/endpoints-java.

**Comment by Aardvarklord** [comment]
Done, thanks.
