### ISSUE TITLE
Client generation from discovery docs fails with AS3.0

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#74]
Hi,

I've got a project which built just fine with AS2.3. Now I've updated to AS3.0 and I'm getting an error when generating the endpoints client library from a discovery file.

`Error:(3634, 20) The method setBatchPath(String) of type MyApi.Builder must override or implement a supertype method`
`Error:(3635, 30) The method setBatchPath(String) is undefined for the type AbstractGoogleJsonClient.Builder`

**Comment by loosebazooka** [comment]
I think you might need to update your google client library dependency to 1.23.0 in your android app.

**Comment by loosebazooka** [comment]
@Burtan any updates?

**Comment by Burtan** [comment]
Updating the client lib helped 👍🏻. Thanks!
