### ISSUE TITLE
Generated openapi.json doesn't have a type with enums

### ISSUE THREAD

**Issue by karim-fc** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#84]
When creating a openapi.json by `gradle endpointsOpenApiDocs`, all the enums have no type in the json. Clients who want to generate client code are getting issues with that. 

In the specification it is also described as such:
https://swagger.io/docs/specification/2-0/enums/

**Comment by loosebazooka** [comment]
@tangiel this appears to be a core library issue?

**Comment by tangiel** [comment]
Can you show a fragment of what you're seeing?

**Comment by karim-fc** [comment]
java:
```
public enum Channel {
	belgianfootball, voetbalvlaanderen, acff
}
```
openapi.json:
```

"definitions": {

...

"Channel": {
   "enum": [
    "belgianfootball",
    "voetbalvlaanderen",
    "acff"
   ]
  },

...

}
```


The client is using a java swagger parser to generate the endpoint clients. It fails to generate the code, until they edit the openapi.json file themselves and add "type": "string" to the enum definition:

```
"Channel": {
   "type": "string",
   "enum": [
    "belgianfootball",
    "voetbalvlaanderen",
    "acff"
   ]
  }
```

**Comment by tangiel** [comment]
https://github.com/cloudendpoints/endpoints-java/pull/149 should fix this.
