### ISSUE TITLE
Could not find any convention object of type WarPluginConvention.

### ISSUE THREAD

**Issue by mayur-patil** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#86]
When trying to use `endpoints-framework-gradle-plugin` I am getting `java.lang.IllegalStateException: Could not find any convention object of type WarPluginConvention.`  I tried with two different versions `1.0.2` and `2.0.0`

**Comment by loosebazooka** [comment]
Have you applied the `war` plugin?

**Comment by JoeWang1127** [comment]
close as not planned
