### ISSUE TITLE
Kotlin support for server-side

### ISSUE THREAD

**Issue by uny** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#87]
If a server-side gradle project, which means the project with `com.google.cloud.tools.endpoints-framework-server` gradle plugin, only has Kotlin source files, appengineRun will complain that
```
* What went wrong:
A problem was found with the configuration of task ':endpointsDiscoveryDocs'.
> Directory '/path/to/project/build/classes/java/main' specified for property 'classesDir' does not exist.
```
Creating a dummy Java class is a workaround.

**Comment by loosebazooka** [comment]
Looks like you might be using an older version of the plugin? Can you confirm what version of endpoints-framework-server you are using?

**Comment by uny** [comment]
I was careless.
I followed this [tutorial](https://cloud.google.com/endpoints/docs/frameworks/java/set-up-environment), and used v1.0.2.
`classpath 'com.google.cloud.tools:endpoints-framework-gradle-plugin:1.0.2'`
Updating to v2.0.0 solves the problem.
Thank you for your help.
